{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 24, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026502C1D930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502C1D930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502C1D930>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_all_fields", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650471F7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650471F7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650471F7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_question_type_eq_STAAR", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504666BC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504666BC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504666BC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_question_type_eq_Mathworld", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026502EC21A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502EC21A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502EC21A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_question_type_eq_Blank", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026502B1BD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502B1BD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502B1BD60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_question_type_college_level_with_whitespace", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650470DA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650470DA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650470DA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_question_type_numeric", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504874A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504874A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504874A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_question_type_special_char", "rerun": "0"}, "7": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026502BC0D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502BC0D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502BC0D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_numeric", "rerun": "0"}, "8": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504874EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504874EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504874EE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_blank_char", "rerun": "0"}, "9": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504674970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504674970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504674970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_TSI", "rerun": "0"}, "10": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504899630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504899630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504899630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_ACT", "rerun": "0"}, "11": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504A3EBC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504A3EBC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504A3EBC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_ACT_with_whitespace", "rerun": "0"}, "12": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026502EA1E70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502EA1E70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502EA1E70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_invalid_special_symbol", "rerun": "0"}, "13": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504607B20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504607B20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504607B20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_blank", "rerun": "0"}, "14": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000265047E0190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265047E0190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265047E0190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_eq_neg_5", "rerun": "0"}, "15": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650498F1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650498F1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650498F1F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_eq_neg_15", "rerun": "0"}, "16": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650479CFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650479CFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650479CFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_invalid_char", "rerun": "0"}, "17": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000265048F7100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265048F7100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265048F7100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_add_2_types_of_classifications", "rerun": "0"}, "18": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026502EA3A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502EA3A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026502EA3A00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_add_2_SAT_with_whitespace", "rerun": "0"}, "19": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650489DA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650489DA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650489DA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_add_2_TSI_with_whitespace", "rerun": "0"}, "20": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650459C5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650459C5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650459C5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_add_2_ACT_with_whitespace", "rerun": "0"}, "21": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000265047F9270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265047F9270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000265047F9270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_malformed", "rerun": "0"}, "22": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000026504A0A5F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504A0A5F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026504A0A5F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_college_level", "rerun": "0"}, "23": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002650485FA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650485FA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /question/college/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002650485FA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_classification_type_STAAR", "rerun": "0"}}, "suite_name": "tests/question_tests/test_college_create_as_admin.py"}}}, "date": "August 11, 2023", "start_time": 1691794961.8081794, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "24", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "24"}